
import { Language } from './types';

export const TRANSLATIONS = {
  en: {
    welcome: "Welcome to your Pro Trading Hub",
    welcomeSub: "Track, Analyze, and Master your Strategies.",
    getStarted: "Get Started",
    strategies: "Trading Strategies",
    addStrategy: "Add New Strategy",
    noStrategies: "No strategies found. Create one to begin.",
    delete: "Delete",
    rename: "Rename",
    months: "Months",
    addMonth: "Add Month",
    winRate: "Win Rate",
    netProfit: "Net Profit",
    trades: "Trades",
    equityCurve: "Equity Curve",
    date: "Day", 
    pair: "Pair",
    dir: "Dir",
    rr: "R:R",
    result: "Result",
    pnlD: "P/L ($)",
    pnlP: "P/L (%)",
    maxRr: "Max Potential",
    notes: "Notes & Observations",
    notesPlaceholder: "Write your analysis, market conditions, or psychological state here...",
    aiEditor: "AI Coach Analysis", // Changed
    aiPrompt: "Ask Gemini...",
    generate: "Analyze",
    processing: "Thinking...",
    uploadImg: "Upload Chart Image",
    loginGoogle: "Sign in with Google",
    logout: "Log out",
    settings: "Settings",
    theme: "Theme",
    language: "Language",
    profile: "Profile",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    persian: "Persian",
    english: "English",
    loginTitle: "Sign in to TradeFlow",
    loginSub: "Sync your data across devices and access AI features.",
    continueGuest: "Continue as Guest",
    dashboard: "Dashboard",
    signIn: "Sign In",
    guest: "Guest User",
  },
  fa: {
    welcome: "به مرکز تجاری حرفه‌ای خود خوش آمدید",
    welcomeSub: "استراتژی‌های خود را ردیابی، تحلیل و تسلط پیدا کنید.",
    getStarted: "شروع کنید",
    strategies: "استراتژی‌های معاملاتی",
    addStrategy: "افزودن استراتژی جدید",
    noStrategies: "استراتژی یافت نشد. برای شروع یکی بسازید.",
    delete: "حذف",
    rename: "تغییر نام",
    months: "ماه‌ها",
    addMonth: "افزودن ماه",
    winRate: "نرخ برد",
    netProfit: "سود خالص",
    trades: "معاملات",
    equityCurve: "منحنی سرمایه",
    date: "روز",
    pair: "جفت ارز",
    dir: "جهت",
    rr: "ریسک:ریوارد",
    result: "نتیجه",
    pnlD: "سود/ضرر ($)",
    pnlP: "سود/ضرر (%)",
    maxRr: "حداکثر پتانسیل",
    notes: "یادداشت‌ها و مشاهدات",
    notesPlaceholder: "تحلیل‌ها، شرایط بازار یا وضعیت روانی خود را بنویسید...",
    aiEditor: "تحلیل هوشمند مربی", // Changed
    aiPrompt: "از جمنای بپرسید...",
    generate: "تحلیل",
    processing: "در حال پردازش...",
    uploadImg: "آپلود تصویر نمودار",
    loginGoogle: "ورود با گوگل",
    logout: "خروج از حساب",
    settings: "تنظیمات",
    theme: "پوسته",
    language: "زبان",
    profile: "پروفایل",
    darkMode: "حالت تاریک",
    lightMode: "حالت روشن",
    persian: "فارسی",
    english: "انگلیسی",
    loginTitle: "ورود به ترید فلو",
    loginSub: "همگام‌سازی داده‌ها و دسترسی به هوش مصنوعی.",
    continueGuest: "ادامه به عنوان مهمان",
    dashboard: "داشبورد",
    signIn: "ورود به حساب",
    guest: "کاربر مهمان",
  }
};

export const INITIAL_STRATEGIES = [
  {
    id: '1',
    name: 'ICT Silver Bullet',
    note: 'Focus on the 10AM - 11AM NY session window. Look for FVG retracements.',
    months: [
      {
        id: 'm1',
        name: 'October 2023',
        note: 'High volatility month due to NFP news events.',
        trades: [
          { id: 't1', date: '01', pair: 'EURUSD', direction: 'Long', rr: 2, result: 'Win', pnlDollar: 500, pnlPercent: 2, maxRr: 3.5 },
          { id: 't2', date: '02', pair: 'EURUSD', direction: 'Short', rr: 2, result: 'Loss', pnlDollar: -250, pnlPercent: -1, maxRr: 0 },
        ]
      }
    ]
  }
] as const;
